"""Run the drop-day playbook end to end with the crystals deliberately ignored.

**Why this exists.** A code audit on 2026-09-23 found that the documented drop-day path
could not execute on a blind test set at all: `boltz_depth.py plan` had no `--csv`,
`score` needed a crystal per ligand, `build_submission.choose_poses()` required two files
that only exist once crystals have been used, three scripts in the printed path imported
`modal` at module scope, and the reference-pose generator the selector depends on covered
only the 87 validation ligands. Each gap was small; together they were the difference
between an hour and a day, and none of the workarounds had ever been exercised.

This is the acceptance test for closing them, and the repo's own standing rule is the
reason it exists: **a pipeline that has never been run is not a pipeline** (README Traps 2,
playbook T6). It takes the 87 validation ligands, hides every crystal-derived column, runs
the playbook's own sequence, and only then unblinds and checks the result against the board
those crystals produce:

    selected 0.6164 · oracle 0.6975 · random 0.5769 · gain +0.0395 · rho -0.2582
    correct sign 75.86%     (FINDINGs 011/035/036/037, reproduced to four decimals)

**What is and is not being tested.** Generation is not: the pool is the existing val87b
Boltz pool, re-presented in the FLAT layout Explorer's `collect` writes, because what
failed was the plumbing around generation rather than the co-folder. Everything downstream
of the pool is executed for real, through the same entry points drop day will use.

**What "blind" means here, precisely.** The ligand table is reduced to `id,smiles` - no
`pdb`, no `cls`, no `fe` - and nothing in the path reads `poses_scored_val87b.csv`,
`validation_ligands.csv` or any deposited structure until `unblind`. The reference set is
the frozen `reference_set_cyp3a4.npz`, which is built from other ENGINES' predictions and
contains nothing from a crystal; on a real blind set it is generated by
`openprotein_cofold.py submit --sweep ... && refset`, which refuses below depth 4.

    python scripts/ops/blind_rehearsal.py run
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "scripts" / "submit"))

from cypstruct.paths import DATA_PROCESSED, SCRATCH  # noqa: E402

TAG = "val87blind"
ARM = "unsteered"
SRC_POOL = Path("D:/cyp_scratch/val87b_unsteered")      # the existing per-ligand pool
FLAT = Path("D:/cyp_scratch/rehearsal_flat")            # hardlinks, not a copy
WORK = SCRATCH / "blind_rehearsal"
OUT_JSON = DATA_PROCESSED / "blind_rehearsal.json"
ZIP = REPO / "submissions" / "02_blind_rehearsal_val87b.zip"

# the board this must reproduce once unblinded, quoted from three independent findings
BOARD = {"selected": 0.6164, "oracle": 0.6975, "random": 0.5769, "gain": 0.0395,
         "rho": -0.2582, "correct_sign": 0.7586}


def _run(cmd: list[str], label: str) -> dict:
    print(f"\n$ {' '.join(cmd)}", flush=True)
    r = subprocess.run([sys.executable] + cmd, capture_output=True, text=True,
                       cwd=str(REPO), timeout=7200)
    tail = (r.stdout or "")[-2500:]
    print(tail, flush=True)
    if r.returncode != 0:
        print((r.stderr or "")[-1500:], flush=True)
    return {"step": label, "rc": r.returncode, "stdout_tail": tail,
            "stderr_tail": (r.stderr or "")[-800:]}


def make_blind_csv(dest: Path) -> dict:
    """`id,smiles` only. Dropping the columns is the whole blind: `pdb` is what every
    crystal lookup keys on and `fe`/`cls` are the binding-mode answer."""
    full = pd.read_csv(DATA_PROCESSED / "validation_ligands.csv")
    blind = full[["id", "smiles"]].copy()
    dest.parent.mkdir(parents=True, exist_ok=True)
    blind.to_csv(dest, index=False)
    return {"n": int(len(blind)), "columns_kept": list(blind.columns),
            "columns_hidden": [c for c in full.columns if c not in blind.columns],
            "out": str(dest)}


def make_flat_pool() -> dict:
    """Re-present the per-ligand pool as Explorer's `collect` writes it.

    HARDLINKS, not copies: the pool is 606 MB and D: has ~12 GB free (T9). The point is
    the LAYOUT - a flat directory of `<lig>__<sample>.cif` - which `build_xeng_feature`
    skipped entirely before `--pool-flat` existed, printing "no poses read from the pool".
    """
    if FLAT.exists() and any(FLAT.glob("*.cif")):
        n = len(list(FLAT.glob("*.cif")))
        return {"reused": True, "poses": n,
                "ligands": len({f.name.split("__")[0] for f in FLAT.glob("*.cif")})}
    FLAT.mkdir(parents=True, exist_ok=True)
    n = 0
    for d in sorted(SRC_POOL.glob("*__*")):
        if not d.is_dir():
            continue
        lig = d.name.split("__")[0]
        for f in sorted(d.glob("*.cif")):
            tgt = FLAT / f"{lig}__{f.stem}.cif"
            if not tgt.exists():
                os.link(f, tgt)
            n += 1
    return {"reused": False, "poses": n,
            "ligands": len({f.name.split("__")[0] for f in FLAT.glob("*.cif")})}


def unblind(picks: dict) -> dict:
    """Now, and only now, open the crystals and check the selection against the board."""
    from scipy import stats

    pool = pd.read_csv(DATA_PROCESSED / f"poses_scored_val87b.csv")
    pool = pool[pool.arm == ARM]
    xe = pd.read_csv(DATA_PROCESSED / f"xeng_{TAG}.csv")
    # the blind pipeline names a pose `<lig>__<sample>`; the scored table names it
    # `<sample>`. Split on the separator, never on position.
    xe["orig_sample"] = xe["sample"].str.split("__").str[-1]
    m = pool.merge(xe[["ligand", "orig_sample", "xeng"]],
                   left_on=["ligand", "sample"], right_on=["ligand", "orig_sample"],
                   how="inner")

    truth = {(r.ligand, r.sample): r.lddt_pli for r in pool.itertuples()}
    rows = []
    for lig, sample in sorted(picks.items()):
        orig = sample.split("__")[-1]
        g = pool[pool.ligand == lig]
        if not len(g):
            continue
        rows.append({"ligand": lig, "picked": orig,
                     "lddt_pli": truth.get((lig, orig), float("nan")),
                     "random": float(g.lddt_pli.mean()),
                     "oracle": float(g.lddt_pli.max())})
    t = pd.DataFrame(rows).dropna(subset=["lddt_pli"])

    # the incumbent path, run on the SAME pool with the crystals available
    from build_submission import choose_poses
    normal = choose_poses("val87b", ARM)
    same = sum(1 for lig, s in normal.items()
               if picks.get(lig, "").split("__")[-1] == s)

    rhos = []
    for _l, g in m.groupby("ligand"):
        gg = g.dropna(subset=["xeng", "lddt_pli"])
        if len(gg) >= 5 and gg.xeng.nunique() > 1:
            rhos.append(stats.spearmanr(gg.xeng, gg.lddt_pli).statistic)
    rhos = [r for r in rhos if r == r]

    rhos = np.asarray(rhos)
    got = {"selected": round(float(t.lddt_pli.mean()), 4),
           "oracle": round(float(t.oracle.mean()), 4),
           "random": round(float(t.random.mean()), 4),
           "gain": round(float((t.lddt_pli - t.random).mean()), 4),
           "rho": round(float(rhos.mean()), 4),
           # "correct sign 75.86%" in the findings is the fraction of ligands whose
           # WITHIN-LIGAND rho has the expected (negative) sign - 66 of 87 - not the
           # fraction of ligands where the pick beat the pool mean. Both are reported,
           # because reading the second as the first is how a matching pipeline looks
           # like a broken one.
           "correct_sign": round(float((rhos < 0).mean()), 4)}
    got_extra = {"frac_beating_pool_mean": round(float((t.lddt_pli > t.random).mean()), 4),
                 "n_rho": int(len(rhos))}
    return {
        "n_ligands": int(len(t)),
        "board_expected": BOARD,
        "board_measured_blind": got,
        "also": got_extra,
        "matches_board": {k: bool(abs(got[k] - BOARD[k]) < 1e-3) for k in BOARD},
        "all_six_match": all(abs(got[k] - BOARD[k]) < 1e-3 for k in BOARD),
        "same_pose_as_crystal_path": f"{same}/{len(normal)}",
        "crystal_path_ligands": len(normal),
        "n_exact_zero_lddt": int((t.lddt_pli == 0).sum()),
        "worst_ligands": t.nsmallest(5, "lddt_pli")[
            ["ligand", "lddt_pli", "random", "oracle"]].to_dict("records"),
    }


def gates() -> dict:
    """Exercise the REFUSALS, which are half of what G6 is for.

    A generator that quietly produces a thin reference set is worse than no generator: the
    feature measures -0.0055 at depth 1 and the only downstream symptom is
    `build_submission` choosing a different rule without saying so. So each gate is run
    here against a deliberately broken input and its counts recorded, because a filter
    that never fires beats any passing check (T8).
    """
    import sys as _sys

    _sys.path.insert(0, str(REPO / "src"))
    from cypstruct import xengine as X

    out: dict = {}
    # --- gate 1: a reference set thinned to depth 1 on 10 ligands --------------
    ref = X.load_reference(DATA_PROCESSED / "reference_set_cyp3a4.npz")
    thinned = sorted(ref)[:10]
    for lig in thinned:
        ref[lig] = ref[lig][:1]
    thin_npz = WORK / "thin_reference.npz"
    X.save_reference(ref, thin_npz)
    out["thinned_ligands"] = thinned

    r = _run(["scripts/structure/build_xeng_feature.py", "--tag", "thinprobe",
              "--pool", str(FLAT), "--pool-flat", "--ref-npz", str(thin_npz)],
             "xeng_refuses_thin")
    out["refuses_without_skip_thin"] = (r["rc"] == 2)
    out["refusal_text"] = r["stdout_tail"][-400:]

    r = _run(["scripts/structure/build_xeng_feature.py", "--tag", "thinprobe",
              "--pool", str(FLAT), "--pool-flat", "--ref-npz", str(thin_npz),
              "--skip-thin"], "xeng_skip_thin")
    out["skip_thin_rc"] = r["rc"]
    out["skip_thin_text"] = r["stdout_tail"][-400:]
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["run", "gates"], nargs="?", default="run")
    a = ap.parse_args()
    if a.cmd == "gates":
        WORK.mkdir(parents=True, exist_ok=True)
        make_flat_pool()
        g = gates()
        print(json.dumps(g, indent=1))
        return 0 if g["refuses_without_skip_thin"] else 1

    WORK.mkdir(parents=True, exist_ok=True)
    rep: dict = {"tag": TAG, "steps": []}

    blind_csv = WORK / "blind_ligands.csv"
    rep["step0_blind_csv"] = make_blind_csv(blind_csv)
    print(json.dumps(rep["step0_blind_csv"], indent=1))

    rep["step0_flat_pool"] = make_flat_pool()
    print(json.dumps(rep["step0_flat_pool"], indent=1))

    # Step 2 - plan. Generation itself is not re-run; this proves the flag exists and
    # that every blind ligand gets a YAML from the same build_yaml the pool came from.
    rep["steps"].append(_run(
        ["scripts/explorer/boltz_depth.py", "plan", "--csv", str(blind_csv),
         "--tag", TAG], "plan"))

    # Step 3 - score must REFUSE rather than return zero rows (G2)
    rep["steps"].append(_run(
        ["scripts/explorer/boltz_depth.py", "score", "--tag", TAG], "score_refuses"))

    # Step 5 - type the ligands prediction-side, from the pool alone (G7)
    rep["steps"].append(_run(
        ["scripts/structure/binding_mode_robustness.py", "predict",
         "--pool", str(FLAT), "--pool-flat", "--ligands", str(blind_csv),
         "--out", str(WORK / "binding_mode_pred.csv")], "binding_mode_predict"))

    # Step 4 - the selection feature, flat pool + frozen reference (G4/G6)
    rep["steps"].append(_run(
        ["scripts/structure/build_xeng_feature.py", "--tag", TAG,
         "--pool", str(FLAT), "--pool-flat",
         "--ref-npz", str(DATA_PROCESSED / "reference_set_cyp3a4.npz")], "build_xeng"))

    # Steps 6+7 - select and build the zip, with no crystals anywhere (G5)
    rep["steps"].append(_run(
        ["scripts/submit/build_submission.py", "build", "--blind",
         "--tag", TAG, "--pool-dir", str(FLAT), "--pool-flat",
         "--ligands", str(blind_csv), "--heme", "keep",
         "--out", str(ZIP)], "build_submission_blind"))

    # Step 8 - validate
    rep["steps"].append(_run(
        ["scripts/submit/build_submission.py", "validate", "--zip", str(ZIP),
         "--ligands", str(blind_csv), "--expect-n", "87"], "validate"))

    bad = [s["step"] for s in rep["steps"]
           if s["rc"] != 0 and s["step"] != "score_refuses"]
    rep["failed_steps"] = bad
    rep["score_refused_as_designed"] = rep["steps"][1]["rc"] != 0

    sub = json.loads((DATA_PROCESSED / f"submission_report_{TAG}.json").read_text())
    rep["selection"] = sub.get("selection")
    rep["unblind"] = unblind(sub["picks"])

    OUT_JSON.write_text(json.dumps(rep, indent=1))
    print("\n" + "=" * 70)
    print(json.dumps({"failed_steps": bad,
                      "score_refused_as_designed": rep["score_refused_as_designed"],
                      "unblind": rep["unblind"]}, indent=1))
    print(f"\n-> {OUT_JSON}")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
